# Config for running tests on localhost
#
# To be compiled on the local computer
#
# (c) Koheron

# Local config does not contain dev_mem

# Executable name
server-name: kserverd

cross-compile: ""

arch_flags:
  - march=native

defines:
  - DEBUG_KSERVER
  # - RELEASE_KSERVER
  - LOCAL

debug:
  status: no # set to yes to compile in debug mode
  flags:
    - rdynamic
    - g

# Optimization is deactivated when compiled in debug mode
optimization_flags:
  - O3
  - finline-limit=150

middleware-path: tmp/middleware

copy_devices_to_middleware: yes

devices:
    - tests/tests.hpp
    # - tests/eigen_tests.hpp
    - tests/hello_world.hpp
