# Config for running tests on localhost
#
# To be compiled on the local computer
#
# (c) Koheron

# Local config does not contain dev_mem

# Target host
host: local

cross-compile: ""

arch_flags:
  - march=native

defines:
  - DEBUG_KSERVER
  # - RELEASE_KSERVER
  - LOCAL

devices:
    - tests/tests.hpp
    #- middleware/eigen_tests.hpp
