# Configuration file for ARM/Ubuntu
#
# (c) Koheron

# Target host
host: armhf

cross-compile: /usr/bin/arm-linux-gnueabihf-

arch_flags:
  - march=armv7-a
  - mtune=cortex-a9
  - mfpu=vfpv3
  #- mfpu=neon
  - mfloat-abi=hard

defines:
  - DEBUG_KSERVER
  # - RELEASE_KSERVER

zynq_sdk_path: &zynq_sdk tmp/zynq-sdk

devices:
  - tests/tests.hpp
  - !!python/object/apply:os.path.join [*zynq_sdk, drivers/device_memory/device_memory.hpp]

requirements:
  - type: git
    src: https://github.com/Koheron/zynq-sdk.git
    branch: master
    dest: *zynq_sdk

  - type: folder
    from: *zynq_sdk
    import: drivers/lib