# Config for running tests on localhost
#
# To be compiled on the local computer
#
# (c) Koheron

# Local config does not contain dev_mem

# Executable name
server-name: kserverd

cross-compile: ""

arch_flags:
  - march=native

defines:
  - DEBUG_KSERVER
  # - RELEASE_KSERVER
  - LOCAL

debug:
  status: no # set to yes to compile in debug mode
  flags:
    - rdynamic
    - g

# Optimization is disactivated when compiled in debug mode
optimization_flags:
  - O3

# This is required for DevMem.
# TODO Remove DevMem dependency in serveur core
zynq_sdk_path: &zynq_sdk tmp/zynq-sdk

requirements:
  - type: git
    src: https://github.com/Koheron/zynq-sdk.git
    branch: master
    dest: *zynq_sdk

  - type: folder
    from: *zynq_sdk
    import: drivers/lib

devices:
    - tests/tests.hpp
    - tests/eigen_tests.hpp